.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PICTURA\-MEDIOCRITAS" "1" "December 2018" "Lounge<C++>" ""
.
.SH "NAME"
\fBpictura\-mediocritas\fR \- Like aurea mediocritas, but with frames in a video instead
.
.SH "SYNOPSIS"
\fBpictura\-mediocritas\fR \fIIN_VIDEO\fR [OUT_IMAGE]
.
.SH "DESCRIPTION"
Like aurea mediocritas, but with frames in a video instead\.
.
.P
Or, you know, get an average frame from a video\.
.
.SH "OPTIONS"
\fIIN_VIDEO\fR
.
.IP "" 4
.
.nf

Video to average, must exist\.
.
.fi
.
.IP "" 0
.
.P
[OUT_IMAGE]
.
.IP "" 4
.
.nf

Image to write the averaged frame to\.

The parent directory must exist\.

Default: IN_VIDEO, but the extension is "png" instead\.
.
.fi
.
.IP "" 0
.
.SH "AUTHOR"
Written by nabijaczleweli <\fInabijaczleweli@gmail\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/LoungeCPP/PicturaMediocritas/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/LoungeCPP/PicturaMediocritas\fR>
